### ISSUE TITLE
Database uniref30_2202_db does not exist while running colabfold local

### ISSUE THREAD

**Issue by nash73b91203005** [nf-core/proteinfold#121]
### Description of the bug

The python code search.py cannot find uniref30_2202_db even though I already specified the path. Maybe I lost something important? Thanks a lot in advance.

ERROR ~ Error executing process > 'NFCORE_PROTEINFOLD:COLABFOLD:MMSEQS_COLABFOLDSEARCH (T478K_T1)'
Caused by:
  Process `NFCORE_PROTEINFOLD:COLABFOLD:MMSEQS_COLABFOLDSEARCH (T478K_T1)` terminated with an error exit status (1)
Traceback (most recent call last):
    File "/colabfold_batch/colabfold-conda/bin/colabfold_search", line 8, in <module>
      sys.exit(main())
    File "/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/mmseqs/search.py", line 444, in main
      threads=args.threads,
    File "/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/mmseqs/search.py", line 66, in mmseqs_search_monomer
      raise FileNotFoundError(f"Database {db} does not exist")
  FileNotFoundError: Database uniref30_2202_db does not exist

### Command used and terminal output

```console
nextflow -bg run nf-core/proteinfold --input samplesheet.csv --outdir ./ --mode colabfold --colabfold_server local --num_recycle 3 --use_amber false --colabfold_model_preset AlphaFold2-ptm --use_gpu false --db_load_mode 0 -profile docker --colabfold_db_path ./colabfold_envdb_202108 --uniref30_path ./uniref30_2202_db --colabfold_alphafold2_params_path ./alphafold_params_2021-07-14 --max_memory 80.GB --colabfold_db ./
```

**Comment by JoseEspinosa** [comment]
Hi @nash73b91203005 thanks for reporting. Are you sure you provided the correct path to uniref? I tried to reproduce your error and I can only do it when I provide a wrong path to the `--uniref30_path` parameter.

**Comment by JoseEspinosa** [comment]
Closed by inactivity

**Comment by vrennie** [comment]
Hi @JoseEspinosa I have the same issue, directory looks like this, seems as though all files are there. Any ideas what might be going wrong?

Thanks

<img width="678" alt="image" src="https://github.com/user-attachments/assets/bb2e17c4-404b-4987-8b50-c92283202eda">

**Comment by JoseEspinosa** [comment]
Which version of the pipeline are you using?
Could you also provide the command you used to run the pipeline and any config you are using?

**Comment by JoseEspinosa** [comment]
I will close this issue now as I was not able to reproduce it. Feel free to reopen it in case you can provide more information
