### ISSUE TITLE
PDBMMCIF download error

### ISSUE THREAD

**Issue by Nicobouch** [nf-core/proteinfold#96]
### Description of the bug

I get the following error on two different clusters:
Error executing process > 'NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:DOWNLOAD_PDBMMCIF'

Any clue of what could be wrong ? is it on my side ? 

### Command used and terminal output

```console
> nextflow run proteinfold-dev --input sample_alpha.csv --outdir alpha_nfcore --mode alphafold2 -profile genotoul

[d0/00f014] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:INPUT_CHECK:SAMPLESHEET_CHECK (sample_alpha.csv)                                                               [100%] 1 of 1 ✔
[d5/d4257e] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_SMALL_BFD:ARIA2 (https://storage.googleapis.com/alphafold-databases/reduced_db... [100%] 1 of 1 ✔
[8e/17eac7] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_SMALL_BFD:GUNZIP (bfd-first_non_consensus_sequences.fasta.gz)                     [100%] 1 of 1 ✔
[9b/5e26d3] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_ALPHAFOLD2_PARAMS:ARIA2 (https://storage.googleapis.com/alphafold/alphafold_pa... [100%] 1 of 1 ✔
[3e/02e21d] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_ALPHAFOLD2_PARAMS:UNTAR (alphafold_params_2022-12-06.tar)                         [100%] 1 of 1 ✔
[9e/a083fa] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_MGNIFY:ARIA2 (https://storage.googleapis.com/alphafold-databases/casp14_versio... [100%] 1 of 1 ✔
[92/a3aa7e] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_MGNIFY:GUNZIP (mgy_clusters_2018_12.fa.gz)                                        [100%] 1 of 1 ✔
[9f/8fa722] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_PDB70:ARIA2 (http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_d... [100%] 1 of 1 ✔
[93/cc6f2c] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_PDB70:UNTAR (pdb70_from_mmcif_200916.tar.gz)                                      [100%] 1 of 1 ✔
[ab/7e2d9d] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:DOWNLOAD_PDBMMCIF                                                                       [100%] 3 of 3, failed: 3..
[ba/1f9c09] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIREF30:ARIA2 (https://storage.googleapis.com/alphafold-databases/v2.3/UniRef... [100%] 1 of 1 ✔
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIREF30:UNTAR (UniRef30_2021_03.tar.gz)                                          -
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIREF90:ARIA2 (ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/un... -
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIREF90:GUNZIP                                                                   -
[70/9b8eb5] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2 (ftp://ftp.wwpdb.org/pub/pdb/derived_data/pdb_seqres.txt)                         [100%] 1 of 1 ✔
[ff/ff29b9] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIPROT_SPROT:ARIA2 (ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release... [100%] 1 of 1 ✔
[c2/4a3af6] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIPROT_SPROT:GUNZIP (uniprot_sprot.fasta.gz)                                     [100%] 1 of 1 ✔
[3f/6e0d5e] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIPROT_TREMBL:ARIA2 (ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_releas... [100%] 1 of 1 ✔
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:ARIA2_UNIPROT_TREMBL:GUNZIP (uniprot_trembl.fasta.gz)                                   -
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:COMBINE_UNIPROT                                                                         -
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:RUN_ALPHAFOLD2                                                                                                 -
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:CUSTOM_DUMPSOFTWAREVERSIONS                                                                                    -
[-        ] process > NFCORE_PROTEINFOLD:ALPHAFOLD2:MULTIQC                                                                                                        -
Error executing process > 'NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:DOWNLOAD_PDBMMCIF'

Caused by:
  Process `NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:DOWNLOAD_PDBMMCIF` terminated with an error exit status (12)

Command executed:

  set -euo pipefail
  
  mkdir raw
  
  rsync \
      --recursive \
      --links \
      --perms \
      --times \
      --compress \
      --info=progress2 \
      --delete \
      --port=33444 \
      rsync.rcsb.org::ftp_data/structures/divided/mmCIF/ \
      raw
  
  echo "Unzipping all mmCIF files..."
  find ./raw -type f -iname "*.gz" -exec gunzip {} +
  
  echo "Flattening all mmCIF files..."
  mkdir mmcif_files
  find ./raw -type d -empty -delete  # Delete empty directories.
  for subdir in ./raw/*; do
      mv "${subdir}/"*.cif ./mmcif_files
  done
  
  # Delete empty download directory structure.
  find ./raw -type d -empty -delete
  
  aria2c \
      ftp://ftp.wwpdb.org/pub/pdb/data/status/obsolete.dat
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_PROTEINFOLD:ALPHAFOLD2:PREPARE_ALPHAFOLD2_DBS:DOWNLOAD_PDBMMCIF":
      sed: $(echo $(sed --version 2>&1) | head -1 | sed 's/^.*GNU sed) //; s/ .*$//')
      rsync: $(rsync --version | head -1 | sed 's/^rsync  version //; s/  protocol version [[:digit:]]*//')
      aria2c: $( aria2c -v | head -1 | sed 's/aria2 version //' )
  END_VERSIONS

Command exit status:
  12

Command output:
  (empty)

Command error:
  rsync: [Receiver] safe_read failed to read 1 bytes: Connection timed out (110)
  rsync error: error in rsync protocol data stream (code 12) at io.c(282) [Receiver=3.2.7]

Work dir:
  /work/project/ijpb/nbouche/work/ab/7e2d9dff49bf09f2f875bfab133e75

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by athbaltzis** [comment]
Hi! It's due to errors in the default PDB mirror. Please try to use another mirror. To do so you need to clone the repo and change the value of the marked parameter in this line (https://github.com/nf-core/proteinfold/blob/master/conf/dbs.config#L17). You have the rest of the options as comments in the same line.
For you reference you can check the following issue: deepmind/alphafold#752

**Comment by Nicobouch** [comment]
Hi, 

I tried the three options. Unsuccessful. 

Tried also to use a local database (on a different cluster) instead : 2023-04-28 containing the following directories :
bfd  mgnify  params  pdb70  pdb_mmcif  pdb_seqres  small_bfd  uniprot  uniref30  uniref90

and setting the --alphafold2_db parameter to --alphafold2_db /shared/bank/alphafold2/2023-04-28 and I get this time the following error:

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  FATAL Flags parsing error: Unknown command line flag 'uniclust30_database_path'. Did you mean: uniref30_database_path ?
  Pass --helpshort or --helpfull to see help on flags.

**Comment by Nicobouch** [comment]
yes I'm using the dev branch (downloaded today).

nextflow run proteinfold-dev --input sample_alpha.csv --outdir alpha_nfcore --mode alphafold2 --alphafold2_db /shared/bank/alphafold2/2023-04-28 --full_dbs=true --alphafold2_model_preset monomer -profile ifb_core

**Comment by Nicobouch** [comment]
This is what I get now with the new version:

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  E0517 00:26:22.859960 47473027692608 hhsearch.py:56] Could not find HHsearch database ./pdb70/pdb70_from_mmcif_200916/pdb70
  Traceback (most recent call last):
    File "/app/alphafold/run_alphafold.py", line 468, in <module>
      app.run(main)
    File "/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/app/alphafold/run_alphafold.py", line 377, in main
      databases=[FLAGS.pdb70_database_path])
    File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
      raise ValueError(f'Could not find HHsearch database {database_path}')
  ValueError: Could not find HHsearch database ./pdb70/pdb70_from_mmcif_200916/pdb70

**Comment by athbaltzis** [comment]
This error looks similar to this issue deepmind/alphafold#518. Please make sure that the pdb70 path above exists in your system and the files have the proper permission so as to be accessible.

**Comment by Nicobouch** [comment]
It was indeed a permission issue. thanks

**Comment by MauriAndresMU1313** [comment]
What kind of permission do I need? Could you specify please? I can not find what kind of permissions needs the ```full_db```
Thank you!
